### ISSUE TITLE
`cldf_form` contains HTML entity encodings (`&#39;`, `&#34;`)

### ISSUE THREAD

**Issue by chrzyki** [lexibank/datsemshift#4]
Hi,

thanks for preparing the dataset! I noticed that the `cldf_form` column contains HTML entity encodings:

```
Execution finished without errors.
Result: 1642 rows returned in 4ms
At line 1:
SELECT * FROM FormTable WHERE FormTable.cldf_form LIKE "%&#%"
```

**Comment by LinguList** [comment]
Oh, possible, the source may have mixed this up. Should we modify the form with `html.unescape`?

**Comment by chrzyki** [comment]
Yes to `html.unescape()`, I think so too. I think it would be best to unescape everything while converting from the HTML files to the tables in `raw/` (i.e. in the original 'values') as `&#39;` etc. were meant to be used in the source as `'` etc. HTML entity encodings are also in the languages (well, it's just one language) and parameters, so I'd fix in an early as stage as possible.

I also wanted to propose a fix in a PR and rebuild the `raw/` data but my download of the HTML files is unfortunately very, very slow. I can do that later if you want but I'll have to wait a bit until the download is done. :)

**Comment by LinguList** [comment]
The download is extremely slow, unfortunately. I can send you the HTML directly, so you could propose any specific fixes there. However, one thing one should keep in mind, is that it may require additional work, since Concepticon has the HTML entities there as well, in the "GLOSS_IN_SOURCE" column.

**Comment by LinguList** [comment]
So one would have to change the `lexibank_datsemshift.py` script as well and make sure to not break it. If you could check this, this would be great. I'll make a link with downloaded data soon and send it privately.

**Comment by chrzyki** [comment]
https://github.com/lexibank/datsemshift/tree/fix-html-entity-encoding has commits and updates from the raw data that *should* fix most of the HTML entity encoding issues. I'm still checking the parameters/shifts to make sure that nothing got broken there, but it seems okay (as of yet...).
